/**
 * Showdown paste species names don't change when holding a Mega Stone — e.g.
 * "Metagross @ Metagrossite" stays "Metagross", with the mega form only implied
 * by the item. Maps a normalized (see normalizeSpeciesKey) item name to the
 * form suffix it implies, so resolveSpeciesImage can prefer the mega sprite
 * over the base one.
 */
export const MEGA_STONE_SUFFIX_BY_ITEM: Record<string, string> = {
  venusaurite: "Mega",
  "charizardite-x": "Mega-X",
  "charizardite-y": "Mega-Y",
  blastoisite: "Mega",
  beedrillite: "Mega",
  pidgeotite: "Mega",
  alakazite: "Mega",
  slowbronite: "Mega",
  gengarite: "Mega",
  kangaskhanite: "Mega",
  pinsirite: "Mega",
  gyaradosite: "Mega",
  aerodactylite: "Mega",
  "mewtwonite-x": "Mega-X",
  "mewtwonite-y": "Mega-Y",
  ampharosite: "Mega",
  steelixite: "Mega",
  scizorite: "Mega",
  heracronite: "Mega",
  houndoominite: "Mega",
  tyranitarite: "Mega",
  sceptilite: "Mega",
  blazikenite: "Mega",
  swampertite: "Mega",
  gardevoirite: "Mega",
  sablenite: "Mega",
  mawilite: "Mega",
  aggronite: "Mega",
  medichamite: "Mega",
  manectite: "Mega",
  sharpedonite: "Mega",
  cameruptite: "Mega",
  altarianite: "Mega",
  banettite: "Mega",
  absolite: "Mega",
  glalitite: "Mega",
  salamencite: "Mega",
  metagrossite: "Mega",
  latiasite: "Mega",
  latiosite: "Mega",
  lopunnite: "Mega",
  garchompite: "Mega",
  lucarionite: "Mega",
  abomasite: "Mega",
  galladite: "Mega",
  audinite: "Mega",
  diancite: "Mega",
};
